#############################################################################################################################
######### SARS-CoV-2 XB lineage investigation geocoding #####################################################################
#############################################################################################################################

######### Darlan Candido da Silva, Bernardo Gutierrez #######################################################################

library(ggmap)
library(data.table)

# Register Google API Key
register_google(key = 'AIzaSyDAsgYtiZfcFYN3jEjcWL1c6NlQwEXMXcQ')


######### Operational components #############################################################################################

# Custom 'create_dt' function that builds a dataframe from the ggmap::geocode output

create_dt <- function(x) {
  precision_depth0 <- ifelse(length(x[["results"]][[1]][["address_components"]]) > 0, 
                             list(x[["results"]][[1]][["address_components"]]), 
                             NA)
  # check length from precision depth
  precision_depth1 <- ifelse(is.na(precision_depth0), NA,
                             ifelse(length(precision_depth0[[1]][[1]]$types) > 0,
                                    precision_depth0[[1]][[1]]$types[[1]], 
                                    NA))
  a <- data.table(
    MatchedAddress = ifelse(!is.null(x[["results"]][[1]][["formatted_address"]]),
                            x[["results"]][[1]][["formatted_address"]], NA),
    PrecisionDepth = precision_depth1,
    lon = ifelse(!is.null(x[["results"]][[1]][["geometry"]][["location"]][["lng"]]),
                 x[["results"]][[1]][["geometry"]][["location"]][["lng"]], NA),
    lat = ifelse(!is.null(x[["results"]][[1]][["geometry"]][["location"]][["lat"]]),
                 x[["results"]][[1]][["geometry"]][["location"]][["lat"]], NA)
  )
}

######### Geocoding steps from Google Maps API ###############################################################################

# Input locations in '[division],[country]' format (manually extracted from GISAID metadata file)

# Locations list, filtered sequence set
locations <- c("Arizona, USA", "Florida, USA", "Texas, USA", "Texas, USA", "Texas, USA", "Texas, USA", "Texas, USA",
               "Nuevo Leon, Mexico", "Nuevo Leon, Mexico", "Nuevo Leon, Mexico", "Minnesota, USA", "State of Mexico, Mexico",
               "Veracruz, Mexico", "Colorado, USA", "Colorado, USA", "Sonora, Mexico", "Tamaulipas, Mexico",
               "California, USA", "California, USA", "Nuevo Leon, Mexico", "Nuevo Leon, Mexico", "Nuevo Leon, Mexico",
               "Queretaro, Mexico", "Queretaro, Mexico", "California, USA","Texas, USA", "Pennsylvania, USA",
               "Illinois, USA", "California, USA", "California, USA", "California, USA", "California, USA",
               "California, USA", "Minnesota, USA", "KwaZulu-Natal, South Africa", "KwaZulu-Natal, South Africa",
               "Chiapas, Mexico", "Nuevo Leon, Mexico", "Nuevo Leon, Mexico", "Nuevo Leon, Mexico", "Queretaro, Mexico",
               "Queretaro, Mexico", "Tabasco, Mexico", "Tabasco, Mexico", "Tabasco, Mexico", "Hidalgo, Mexico",
               "Nuevo Leon, Mexico", "Coahuila, Mexico", "Minnesota, USA", "Illinois, USA", "Florida, USA",
               "Florida, USA", "Yucatan, Mexico", "Michoacan, Mexico", "Tamaulipas, Mexico", "Nuevo Leon, Mexico",
               "Nuevo Leon, Mexico", "Tamaulipas, Mexico", "Nuevo Leon, Mexico", "Quintana Roo, Mexico",
               "Zacatecas, Mexico", "State of Mexico, Mexico", "Veracruz, Mexico", "Texas, USA", "Florida, USA",
               "Tamaulipas, Mexico", "Nuevo Leon, Mexico", "Tabasco, Mexico", "Tabasco, Mexico", "Tabasco, Mexico",
               "Tabasco, Mexico", "Tabasco, Mexico", "Maryland, USA", "Arizona, USA", "Quintana Roo, Mexico", "Puebla, Mexico",
               "Puebla, Mexico", "Nuevo Leon, Mexico", "Nuevo Leon, Mexico", "Tabasco, Mexico", "Mexico City, Mexico",
               "Hidalgo, Mexico", "Puebla, Mexico", "Texas, USA", "Tabasco, Mexico", "Nuevo Leon, Mexico", "Nuevo Leon, Mexico",
               "Nuevo Leon, Mexico", "Nuevo Leon, Mexico", "Nuevo Leon, Mexico", "Coahuila, Mexico", "Nuevo Leon, Mexico",
               "Yucatan, Mexico", "Nuevo Leon, Mexico", "Nuevo Leon, Mexico", "Coahuila, Mexico", "Texas, USA", "Texas, USA",
               "Texas, USA", "Guatemala", "Nuevo Leon, Mexico", "Nuevo Leon, Mexico", "Nuevo Leon, Mexico", "Nuevo Leon, Mexico",
               "Nuevo Leon, Mexico", "Nuevo Leon, Mexico", "Nuevo Leon, Mexico", "Nuevo Leon, Mexico", "Nuevo Leon, Mexico",
               "Durango, Mexico", "Nuevo Leon, Mexico", "Nuevo Leon, Mexico", "Nuevo Leon, Mexico", "Quintana Roo, Mexico",
               "Nuevo Leon, Mexico", "Nuevo Leon, Mexico", "California, USA", "California, USA", "Colorado, USA", "Colorado, USA",
               "California, USA", "California, USA", "Cayman Islands", "Utah, USA", "Colorado, USA", "Colorado, USA", "New York, USA",
               "Catalunya, Spain", "Chihuahua, Mexico", "Nuevo Leon, Mexico", "Maryland, USA", "Texas, USA",
               "Texas, USA", "Texas, USA", "Maryland, USA", "New Mexico, USA", "Colorado, USA", "Colorado, USA", "Maryland, USA",
               "Maryland, USA", "Maryland, USA", "Maryland, USA", "California, USA", "California, USA", "Mexico City, Mexico",
               "Mexico City, Mexico", "Madrid, Spain", "State of Mexico, Mexico", "California, USA", "California, USA",
               "California, USA", "California, USA", "California, USA", "California, USA", "California, USA", "California, USA",
               "Copan, Honduras", "New Mexico, USA", "Texas, USA", "Morelos, Mexico", "Chiapas, Mexico", "California, USA",
               "California, USA", "Maryland, USA", "Mexico City, Mexico", "Mexico City, Mexico", "Mexico City, Mexico",
               "Guanajuato, Mexico", "California, USA", "Sao Paulo, Brazil", "Nuevo Leon, Mexico", "Texas, USA", "North Carolina, USA",
               "Queretaro, Mexico", "Brazzaville, Republic of the Congo", "Brazzaville, Republic of the Congo",
               "Brazzaville, Republic of the Congo", "Brazzaville, Republic of the Congo", "Brazzaville, Republic of the Congo",
               "Brazzaville, Republic of the Congo", "North Carolina, USA", "North Carolina, USA", "North Carolina, USA", "Minnesota, USA",
               "Brazzaville, Republic of the Congo", "Brazzaville, Republic of the Congo", "Brazzaville, Republic of the Congo",
               "Brazzaville, Republic of the Congo", "Brazzaville, Republic of the Congo", "Brazzaville, Republic of the Congo",
               "Brazzaville, Republic of the Congo", "New York, USA", "Chiapas, Mexico", "Turkey", "South Korea", "California, USA", "Turkey",
               "Turkey", "Turkey", "Brazzaville, Republic of the Congo", "Brazzaville, Republic of the Congo",
               "Brazzaville,Republic of the Congo", "Brazzaville, Republic of the Congo", "Brazzaville, Republic of the Congo",
               "Brazzaville, Republic of the Congo", "Brazzaville, Republic of the Congo", "North Carolina, USA", "New Mexico, USA",
               "Michigan, USA", "Tamaulipas, Mexico", "Puebla, Mexico", "Morelos, Mexico", "Uusimaa, Finland", "Arizona, USA", "New Mexico, USA",
               "New Mexico, USA", "Connecticut, USA", "Wisconsin, USA", "Wisconsin, USA", "Wisconsin, USA", "Wisconsin, USA", "Wisconsin, USA",
               "Wisconsin, USA", "New Mexico, USA", "California, USA", "Turkey", "Turkey", "Turkey", "New York, USA", "Veracruz, Mexico",
               "Texas, USA", "El Salvador", "El Salvador", "El Salvador", "El Salvador", "El Salvador", "El Salvador", "El Salvador", "El Salvador",
               "El Salvador", "El Salvador", "Texas, USA", "Texas, USA", "Texas, USA", "Texas, USA", "Texas, USA", "New York, USA", "New York, USA",
               "California, USA", "Turkey", "Turkey", "Wisconsin, USA", "New Mexico, USA", "Tamaulipas, Mexico", "Colorado, USA", "Colorado, USA",
               "Colorado, USA", "California, USA", "Chihuahua, Mexico", "Texas, USA", "Texas, USA", "Texas, USA", "Texas, USA", "Texas, USA",
               "Illinois, USA", "Illinois, USA", "Turkey", "Turkey", "Illinois, USA", "Georgia, USA", "Texas, USA", "Texas, USA", "Texas, USA",
               "Texas, USA", "Texas, USA", "Texas, USA", "Texas, USA", "Texas, USA", "Texas, USA", "Maryland, USA", "Maryland, USA", "Sonora, Mexico",
               "California, USA", "New Mexico, USA", "California, USA", "Alabama, USA", "Florida, USA", "Wisconsin, USA", "Texas, USA", "Texas, USA",
               "Ohio, USA", "Chiapas, Mexico", "Mexico City, Mexico", "Chiapas, Mexico", "Hidalgo, Mexico", "Chiapas, Mexico", "Wisconsin, USA",
               "New Mexico, USA", "Texas, USA", "California, USA", "Wisconsin, USA", "Texas, USA", "Texas, USA", "Tabasco, Mexico",
               "Aguascalientes, Mexico", "Alabama, USA", "Veracruz, Mexico", "Texas, USA", "Florida, USA", "Texas, USA", "Texas, USA", "Texas, USA",
               "Brno, Czech Republic", "Texas, USA", "Florida, USA", "New York, USA", "New York, USA", "California, USA", "Illinois, USA", "Texas, USA",
               "North Dakota, USA", "North Dakota, USA", "North Dakota, USA", "North Dakota, USA", "Florida, USA", "Texas, USA", "Campania, Italy",
               "Texas, USA", "Texas, USA", "Texas, USA", "Maryland, USA", "Maryland, USA", "Maryland, USA", "Maryland, USA", "Maryland, USA",
               "Maryland, USA", "Georgia, USA", "New York, USA", "California, USA", "Pennsylvania, USA", "Illinois, USA", "California, USA",
               "California, USA", "Veracruz, Mexico", "Texas, USA", "New York, USA", "New York, USA", "Malaysia", "North Carolina, USA", "Maryland, USA",
               "Maryland, USA", "Texas, USA", "Texas, USA", "Oregon, USA", "California, USA", "Honduras", "Honduras", "Jalisco, Mexico",
               "Nuevo Leon, Mexico", "Morelos, Mexico", "State of Mexico, Mexico", "Mexico, Mexico", "Texas, USA", "Texas, USA", "Texas, USA", "Texas, USA",
               "Texas, USA", "Texas, USA", "Texas, USA", "Texas, USA", "New York, USA", "Texas, USA", "Texas, USA", "Pennsylvania, USA", "Texas, USA",
               "Texas, USA", "Texas, USA", "Texas, USA", "Texas, USA", "Texas, USA", "Texas, USA", "Texas, USA", "Texas, USA", "Texas, USA", "Texas, USA",
               "Texas, USA", "Texas, USA", "Texas, USA", "Texas, USA", "Wisconsin, USA", "Colorado, USA", "Colorado, USA", "Madrid, Spain", "Texas, USA",
               "Illinois, USA", "New York, USA", "Illinois, USA", "California, USA", "California, USA", "California, USA", "California, USA",
               "California, USA", "Yucatan, Mexico", "Yucatan, Mexico", "Guanajuato, Mexico", "Mexico City, Mexico", "Tamaulipas, Mexico", "Ohio, USA",
               "Illinois, USA", "Illinois, USA", "Uttar Pradesh, India", "North Carolina, USA", "Wisconsin, USA", "Wisconsin, USA",
               "Region Metropolitana de Santiago, Chile", "California, USA", "California, USA", "California, USA", "California, USA", "California, USA",
               "California, USA", "California, USA", "California, USA", "California, USA", "New York, USA", "New York, USA", "New York, USA",
               "New South Wales, Australia", "California, USA", "California, USA", "California, USA", "New York, USA", "New York, USA", "California, USA",
               "California, USA", "California, USA", "California, USA", "California, USA", "California, USA", "California, USA", "California, USA",
               "California, USA", "Oregon, USA", "California, USA", "California, USA", "California, USA", "California, USA", "California, USA",
               "California, USA", "California, USA", "California, USA", "California, USA", "Oregon, USA", "Minnesota, USA", "Indiana, USA",
               "Mexico City, Mexico", "Mexico City, Mexico", "State of Mexico, Mexico", "State of Mexico, Mexico", "Mexico City, Mexico",
               "Mexico City, Mexico", "State of Mexico, Mexico", "State of Mexico, Mexico", "New Mexico, USA", "Madhya Pradesh, India", "New York, USA",
               "Delhi, India", "Delhi, India", "Delhi, India", "Jammu and Kashmir, India", "Jammu and Kashmir, India", "Oregon, USA", "Yucatan, Mexico",
               "Yucatan, Mexico", "Madrid, Spain", "Madrid, Spain", "Madrid, Spain", "Washington, USA", "Washington, USA", "Arizona, USA",
               "Arizona, USA", "Maryland, USA", "Queretaro, Mexico", "Nuevo Leon, Mexico", "Guanajuato, Mexico", "Guanajuato, Mexico",
               "Oaxaca, Mexico", "San Luis Potosi, Mexico", "Queretaro, Mexico", "Guanajuato, Mexico", "Guanajuato, Mexico", "Guanajuato, Mexico",
               "Puebla, Mexico", "Chiapas, Mexico", "Texas, USA", "Texas, USA", "Texas, USA", "Texas, USA", "Wisconsin, USA", "Delhi, India",
               "Delhi, India", "Delhi, India", "California, USA", "California, USA", "California, USA", "California, USA", "California, USA",
               "California, USA", "California, USA", "California, USA", "California, USA", "Basque Country, Spain", "Sinaloa, Mexico",
               "Jammu and Kashmir, India", "Delhi, India", "Oregon, USA", "Wisconsin, USA", "Wisconsin, USA", "Wisconsin, USA", "Wisconsin, USA",
               "California, USA", "California, USA", "Mexico City, Mexico", "Queretaro, Mexico", "Tamaulipas, Mexico", "Coahuila, Mexico",
               "Mexico City, Mexico", "Mexico City, Mexico", "Minnesota, USA", "Illinois, USA", "Maryland, USA", "Maryland, USA",
               "Madrid, Spain", "Madrid, Spain", "Nevada, USA",
               "Oregon, USA",
               "Mexico City, Mexico",
               "State of Mexico, Mexico",
               "Mexico City, Mexico",
               "State of Mexico, Mexico",
               "California, USA",
               "California, USA",
               "California, USA",
               "California, USA",
               "California, USA",
               "California, USA",
               "California, USA",
               "Hong Kong",
               "California, USA",
               "California, USA",
               "California, USA",
               "California, USA",
               "California, USA",
               "California, USA",
               "California, USA",
               "California, USA",
               "California, USA",
               "California, USA",
               "California, USA",
               "California, USA",
               "California, USA",
               "California, USA",
               "California, USA",
               "California, USA",
               "California, USA",
               "California, USA",
               "California, USA",
               "California, USA",
               "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "North Rhine-Westphalia, Germany",
                     "La Paz, Honduras",
                     "La Paz, Honduras",
                     "Comayagua, Honduras",
                     "Valle, Honduras",
                     "Valle, Honduras",
                     "Valle, Honduras",
                     "Valle, Honduras",
                     "Valle, Honduras",
                     "Francisco Morazan, Honduras",
                     "Choluteca, Honduras",
                     "Atlantida, Honduras",
                     "Cortes, Honduras",
                     "Olancho, Honduras",
                     "Comayagua, Honduras",
                     "Comayagua, Honduras",
                     "La Paz, Honduras",
                     "La Paz, Honduras",
                     "El Paraiso, Honduras",
                     "Francisco Morazan, Honduras",
                     "Francisco Morazan, Honduras",
                     "Francisco Morazan, Honduras",
                     "La Paz, Honduras",
                     "Santa Barbara, Honduras",
                     "Colon, Honduras",
                     "Cortes, Honduras",
                     "Minnesota, USA",
                     "Minnesota, USA",
                     "Florida, USA",
                     "Florida, USA",
                     "Minnesota, USA",
                     "Minnesota, USA",
                     "Minnesota, USA",
                     "Minnesota, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "Rhode Island, USA",
                     "Chihuahua, Mexico",
                     "Arizona, USA",
                     "Arizona, USA",
                     "Nouvelle-Aquitaine, France",
                     "Quintana Roo, Mexico",
                     "Kansas, USA",
                     "Baja California, Mexico",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Jalisco, Mexico",
                     "Morelos, Mexico",
                     "Morelos, Mexico",
                     "Morelos, Mexico",
                     "State of Mexico, Mexico",
                     "Queretaro, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Jalisco, Mexico",
                     "Guanajuato, Mexico",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Mexico City, Mexico",
                     "Veracruz, Mexico",
                     "Maryland, USA",
                     "California, USA",
                     "Hong Kong",
                     "New York, USA",
                     "Minnesota, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "Illinois, USA",
                     "Illinois, USA",
                     "Illinois, USA",
                     "Washington, USA",
                     "Illinois, USA",
                     "Illinois, USA",
                     "Illinois, USA",
                     "Illinois, USA",
                     "Arizona, USA",
                     "Arizona, USA",
                     "Texas, USA",
                     "California, USA",
                     "Texas, USA",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "State of Mexico, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "State of Mexico, Mexico",
                     "State of Mexico, Mexico",
                     "State of Mexico, Mexico",
                     "State of Mexico, Mexico",
                     "State of Mexico, Mexico",
                     "Hidalgo, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "State of Mexico, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "State of Mexico, Mexico",
                     "Madrid, Spain",
                     "Florida, USA",
                     "Florida, USA",
                     "Florida, USA",
                     "Florida, USA",
                     "Florida, USA",
                     "Florida, USA",
                     "California, USA",
                     "California, USA",
                     "Florida, USA",
                     "Florida, USA",
                     "Florida, USA",
                     "California, USA",
                     "Indiana, USA",
                     "Indiana, USA",
                     "Indiana, USA",
                     "Kansas, USA",
                     "Kansas, USA",
                     "Kansas, USA",
                     "Maryland, USA",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "State of Mexico, Mexico",
                     "Mexico City, Mexico",
                     "State of Mexico, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "State of Mexico, Mexico",
                     "State of Mexico, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "State of Mexico, Mexico",
                     "Hidalgo, Mexico",
                     "Sonora, Mexico",
                     "Sonora, Mexico",
                     "Guanajuato, Mexico",
                     "Durango, Mexico",
                     "Durango, Mexico",
                     "Tamaulipas, Mexico",
                     "Puebla, Mexico",
                     "Sonora, Mexico",
                     "Tennessee, USA",
                     "Morelos, Mexico",
                     "California, USA",
                     "California, USA",
                     "Louisiana, USA",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Veracruz, Mexico",
                     "Guanajuato, Mexico",
                     "Guanajuato, Mexico",
                     "San Luis Potosi, Mexico",
                     "Zacatecas, Mexico",
                     "Veracruz, Mexico",
                     "California, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Illinois, USA",
                     "California, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Kansas, USA",
                     "Kansas, USA",
                     "Oregon, USA",
                     "California, USA",
                     "Indiana, USA",
                     "Florida, USA",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Tamaulipas, Mexico",
                     "Tamaulipas, Mexico",
                     "Veracruz, Mexico",
                     "Guanajuato, Mexico",
                     "Durango, Mexico",
                     "Durango, Mexico",
                     "Durango, Mexico",
                     "Chiapas, Mexico",
                     "Tabasco, Mexico",
                     "Coahuila, Mexico",
                     "Tamaulipas, Mexico",
                     "Tamaulipas, Mexico",
                     "Tabasco, Mexico",
                     "Aguascalientes, Mexico",
                     "Mexico City, Mexico",
                     "Texas, USA",
                     "California, USA",
                     "Portugal",
                     "Wales, United Kingdom",
                     "Arizona, USA",
                     "Wisconsin, USA",
                     "Wisconsin, USA",
                     "Texas, USA",
                     "Sinaloa, Mexico",
                     "New Mexico, USA",
                     "New Mexico, USA",
                     "New Mexico, USA",
                     "Minnesota, USA",
                     "State of Mexico, Mexico",
                     "State of Mexico, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "State of Mexico, Mexico",
                     "State of Mexico, Mexico",
                     "Hidalgo, Mexico",
                     "State of Mexico, Mexico",
                     "State of Mexico, Mexico",
                     "State of Mexico, Mexico",
                     "State of Mexico, Mexico",
                     "Tabasco, Mexico",
                     "Coahuila, Mexico",
                     "New Mexico, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "California, USA",
                     "California, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Nevada, USA",
                     "Kansas, USA",
                     "Caribbean, Cayman Islands",
                     "Turkey",
                     "Minnesota, USA",
                     "New York, USA",
                     "New York, USA",
                     "New York, USA",
                     "New York, USA",
                     "New York, USA",
                     "New York, USA",
                     "New York, USA",
                     "New York, USA",
                     "New York, USA",
                     "New York, USA",
                     "New York, USA",
                     "New York, USA",
                     "New York, USA",
                     "New York, USA",
                     "New York, USA",
                     "Tabasco, Mexico",
                     "Zacatecas, Mexico",
                     "Sonora, Mexico",
                     "Morelos, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "State of Mexico, Mexico",
                     "State of Mexico, Mexico",
                     "Coahuila, Mexico",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Tamaulipas, Mexico",
                     "Chiapas, Mexico",
                     "Veracruz, Mexico",
                     "Sonora, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Queretaro, Mexico",
                     "Queretaro, Mexico",
                     "Queretaro, Mexico",
                     "Queretaro, Mexico",
                     "Queretaro, Mexico",
                     "Tabasco, Mexico",
                     "Jalisco, Mexico",
                     "Coahuila, Mexico",
                     "Indiana, USA",
                     "Indiana, USA",
                     "State of Mexico, Mexico",
                     "Mexico City, Mexico",
                     "State of Mexico, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Turkey",
                     "Sinaloa, Mexico",
                     "Sinaloa, Mexico",
                     "Sinaloa, Mexico",
                     "Arizona, USA",
                     "Arizona, USA",
                     "State of Mexico, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "State of Mexico, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Veracruz, Mexico",
                     "Veracruz, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Tamaulipas, Mexico",
                     "Georgia, USA",
                     "Uusimaa, Finland",
                     "Minnesota, USA",
                     "Yucatan, Mexico",
                     "Yucatan, Mexico",
                     "Yucatan, Mexico",
                     "Yucatan, Mexico",
                     "Yucatan, Mexico",
                     "Washington, USA",
                     "California, USA",
                     "California, USA",
                     "Maryland, USA",
                     "Maryland, USA",
                     "District of Columbia, USA",
                     "Louisiana, USA",
                     "Tamaulipas, Mexico",
                     "Tamaulipas, Mexico",
                     "Tamaulipas, Mexico",
                     "Queretaro, Mexico",
                     "Puebla, Mexico",
                     "Pennsylvania, USA",
                     "Pennsylvania, USA",
                     "Pennsylvania, USA",
                     "Alabama, USA",
                     "California, USA",
                     "California, USA",
                     "Puebla, Mexico",
                     "New York, USA",
                     "Vaud, Switzerland",
                     "Maryland, USA",
                     "Maryland, USA",
                     "Maryland, USA",
                     "Maryland, USA",
                     "Maryland, USA",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "State of Mexico, Mexico",
                     "State of Mexico, Mexico",
                     "Mexico City, Mexico",
                     "State of Mexico, Mexico",
                     "State of Mexico, Mexico",
                     "Mexico City, Mexico",
                     "Hidalgo, Mexico",
                     "Veracruz, Mexico",
                     "Washington, USA",
                     "Texas, USA",
                     "California, USA",
                     "California, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Arizona, USA",
                     "Arizona, USA",
                     "Arizona, USA",
                     "Kansas, USA",
                     "Kansas, USA",
                     "Nevada, USA",
                     "Nevada, USA",
                     "Quintana Roo, Mexico",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Tamaulipas, Mexico",
                     "Nuevo Leon, Mexico",
                     "Tamaulipas, Mexico",
                     "Nuevo Leon, Mexico",
                     "Coahuila, Mexico",
                     "Chihuahua, Mexico",
                     "Nuevo Leon, Mexico",
                     "Tamaulipas, Mexico",
                     "Tamaulipas, Mexico",
                     "Chihuahua, Mexico",
                     "Chihuahua, Mexico",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Coahuila, Mexico",
                     "Nuevo Leon, Mexico",
                     "Zacatecas, Mexico",
                     "Guanajuato, Mexico",
                     "Guanajuato, Mexico",
                     "Jalisco, Mexico",
                     "Michoacan, Mexico",
                     "State of Mexico, Mexico",
                     "Oaxaca, Mexico",
                     "State of Mexico, Mexico",
                     "State of Mexico, Mexico",
                     "Veracruz, Mexico",
                     "Hidalgo, Mexico",
                     "Veracruz, Mexico",
                     "Baja California, Mexico",
                     "Arizona, USA",
                     "Vaud, Switzerland",
                     "Campeche, Mexico",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Durango, Mexico",
                     "Chihuahua, Mexico",
                     "Tamaulipas, Mexico",
                     "Sinaloa, Mexico",
                     "Sinaloa, Mexico",
                     "Mexico City, Mexico",
                     "Veracruz, Mexico",
                     "Oaxaca, Mexico",
                     "Veracruz, Mexico",
                     "Veracruz, Mexico",
                     "Veracruz, Mexico",
                     "Veracruz, Mexico",
                     "Colorado, USA",
                     "Colorado, USA",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Missouri, USA",
                     "Mexico City, Mexico",
                     "State of Mexico, Mexico",
                     "Tamaulipas, Mexico",
                     "Veracruz, Mexico",
                     "Veracruz, Mexico",
                     "Veracruz, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "New York, USA",
                     "New York, USA",
                     "New York, USA",
                     "New York, USA",
                     "New York, USA",
                     "Virginia, USA",
                     "Virginia, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "New York, USA",
                     "New York, USA",
                     "New York, USA",
                     "New York, USA",
                     "New York, USA",
                     "Minnesota, USA",
                     "Washington, USA",
                     "Washington, USA",
                     "Washington, USA",
                     "Washington, USA",
                     "Washington, USA",
                     "Washington, USA",
                     "Washington, USA",
                     "Washington, USA",
                     "Texas, USA",
                     "Florida, USA",
                     "California, USA",
                     "California, USA",
                     "Wisconsin, USA",
                     "Wisconsin, USA",
                     "Wisconsin, USA",
                     "Maryland, USA",
                     "Sinaloa, Mexico",
                     "New York, USA",
                     "New York, USA",
                     "New Jersey, USA",
                     "New Jersey, USA",
                     "Maryland, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "Vaud, Switzerland",
                     "Minnesota, USA",
                     "New York, USA",
                     "California, USA",
                     "State of Mexico, Mexico",
                     "Hidalgo, Mexico",
                     "State of Mexico, Mexico",
                     "Baja California Sur, Mexico",
                     "Guanajuato, Mexico",
                     "Veracruz, Mexico",
                     "Veracruz, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Texas, USA",
                     "New Mexico, USA",
                     "New Mexico, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "New Mexico, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "California, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "El Salvador",
                     "El Salvador",
                     "El Salvador",
                     "El Salvador",
                     "El Salvador",
                     "El Salvador",
                     "El Salvador",
                     "El Salvador",
                     "California, USA",
                     "Texas, USA",
                     "Ohio, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "California, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "New Jersey, USA",
                     "New Jersey, USA",
                     "New Jersey, USA",
                     "New Jersey, USA",
                     "California, USA",
                     "Illinois, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "South Carolina, USA",
                     "Texas, USA",
                     "California, USA",
                     "Texas, USA",
                     "New York, USA",
                     "Florida, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "New York, USA",
                     "New York, USA",
                     "California, USA",
                     "New Jersey, USA",
                     "New York, USA",
                     "New York, USA",
                     "Texas, USA",
                     "New York, USA",
                     "Michigan, USA",
                     "Michigan, USA",
                     "California, USA",
                     "Guatemala",
                     "Guatemala",
                     "Guatemala",
                     "Guatemala",
                     "Guatemala",
                     "Guatemala",
                     "Guatemala",
                     "Guatemala",
                     "Guatemala",
                     "Guatemala",
                     "Guatemala",
                     "New York, USA",
                     "California, USA",
                     "Arizona, USA",
                     "Arizona, USA",
                     "Arizona, USA",
                     "Virginia, USA",
                     "New York, USA",
                     "Sonora, Mexico",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Coahuila, Mexico",
                     "Tamaulipas, Mexico",
                     "Tabasco, Mexico",
                     "Tabasco, Mexico",
                     "Oaxaca, Mexico",
                     "Jalisco, Mexico",
                     "Guanajuato, Mexico",
                     "Sonora, Mexico",
                     "San Luis Potosi, Mexico",
                     "Chiapas, Mexico",
                     "Puebla, Mexico",
                     "California, USA",
                     "California, USA",
                     "Louisiana, USA",
                     "California, USA",
                     "Iowa, USA",
                     "Georgia, USA",
                     "California, USA",
                     "Utah, USA",
                     "Iowa, USA",
                     "Mississippi, USA",
                     "Arizona, USA",
                     "Arizona, USA",
                     "Arizona, USA",
                     "Arizona, USA",
                     "Rhode Island, USA",
                     "District of Columbia, USA",
                     "California, USA",
                     "Florida, USA",
                     "California, USA",
                     "Tamaulipas, Mexico",
                     "Nuevo Leon, Mexico",
                     "Mexico City, Mexico",
                     "Nuevo Leon, Mexico",
                     "San Luis Potosi, Mexico",
                     "Morelos, Mexico",
                     "State of Mexico, Mexico",
                     "Mexico City, Mexico",
                     "Nuevo Leon, Mexico",
                     "San Luis Potosi, Mexico",
                     "Nuevo Leon, Mexico",
                     "Zacatecas, Mexico",
                     "San Luis Potosi, Mexico",
                     "Zacatecas, Mexico",
                     "Coahuila, Mexico",
                     "Chihuahua, Mexico",
                     "California, USA",
                     "California, USA",
                     "Veracruz, Mexico",
                     "State of Mexico, Mexico",
                     "Mexico City, Mexico",
                     "Washington, USA",
                     "Maryland, USA",
                     "Maryland, USA",
                     "California, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "New Jersey, USA",
                     "California, USA",
                     "California, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Minnesota, USA",
                     "USA",
                     "New York, USA",
                     "Nevada, USA",
                     "Massachusetts, USA",
                     "California, USA",
                     "Massachusetts, USA",
                     "California, USA",
                     "Turkey",
                     "Turkey",
                     "Colorado, USA",
                     "Colorado, USA",
                     "Massachusetts, USA",
                     "Massachusetts, USA",
                     "Massachusetts, USA",
                     "Massachusetts, USA",
                     "Massachusetts, USA",
                     "Massachusetts, USA",
                     "Massachusetts, USA",
                     "Massachusetts, USA",
                     "Massachusetts, USA",
                     "Massachusetts, USA",
                     "Washington, USA",
                     "Pennsylvania, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "Georgia, USA",
                     "Colorado, USA",
                     "Arizona, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "Florida, USA",
                     "Arizona, USA",
                     "California, USA",
                     "North Carolina, USA",
                     "Texas, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "Nebraska, USA",
                     "California, USA",
                     "Nevada, USA",
                     "Nevada, USA",
                     "Nevada, USA",
                     "Nevada, USA",
                     "Texas, USA",
                     "Washington, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Arizona, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "New Mexico, USA",
                     "Arizona, USA",
                     "Washington, USA",
                     "Washington, USA",
                     "Washington, USA",
                     "Arizona, USA",
                     "Arizona, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Arizona, USA",
                     "New Mexico, USA",
                     "New Mexico, USA",
                     "Nevada, USA",
                     "Texas, USA",
                     "Maryland, USA",
                     "Maryland, USA",
                     "Virginia, USA",
                     "Indiana, USA",
                     "Indiana, USA",
                     "Illinois, USA",
                     "North Carolina, USA",
                     "North Carolina, USA",
                     "Virginia, USA",
                     "North Carolina, USA",
                     "North Carolina, USA",
                     "Texas, USA",
                     "Florida, USA",
                     "Florida, USA",
                     "Florida, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Massachusetts, USA",
                     "Maryland, USA",
                     "Maryland, USA",
                     "Colorado, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Florida, USA",
                     "Iowa, USA",
                     "Coahuila, Mexico",
                     "Morelos, Mexico",
                     "Coahuila, Mexico",
                     "Sonora, Mexico",
                     "Sonora, Mexico",
                     "Tabasco, Mexico",
                     "State of Mexico, Mexico",
                     "New York, USA",
                     "Ohio, USA",
                     "Ohio, USA",
                     "Texas, USA",
                     "Georgia, USA",
                     "Nevada, USA",
                     "Colorado, USA",
                     "Colorado, USA",
                     "Colorado, USA",
                     "Colorado, USA",
                     "Texas, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "Florida, USA",
                     "New York, USA",
                     "Iowa, USA",
                     "Iowa, USA",
                     "Iowa, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "Madrid, Spain",
                     "Madrid, Spain",
                     "New Mexico, USA",
                     "Oregon, USA",
                     "Galapagos, Ecuador",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "Massachusetts, USA",
                     "North Carolina, USA",
                     "New Jersey, USA",
                     "New Jersey, USA",
                     "North Carolina, USA",
                     "North Carolina, USA",
                     "Texas, USA",
                     "Nevada, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "New Mexico, USA",
                     "New Mexico, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Arizona, USA",
                     "New Mexico, USA",
                     "New Mexico, USA",
                     "New Mexico, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "California, USA",
                     "Nevada, USA",
                     "Nevada, USA",
                     "Nevada, USA",
                     "Washington, USA",
                     "Washington, USA",
                     "California, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "California, USA",
                     "California, USA",
                     "Massachusetts, USA",
                     "Iowa, USA",
                     "New Jersey, USA",
                     "Maine, USA",
                     "Maine, USA",
                     "Maine, USA",
                     "Maine, USA",
                     "New Jersey, USA",
                     "New Jersey, USA",
                     "Maryland, USA",
                     "Tamaulipas, Mexico",
                     "Durango, Mexico",
                     "Tabasco, Mexico",
                     "Oaxaca, Mexico",
                     "Queretaro, Mexico",
                     "Chiapas, Mexico",
                     "Oaxaca, Mexico",
                     "Oregon, USA",
                     "Sinaloa, Mexico",
                     "Sinaloa, Mexico",
                     "Guanajuato, Mexico",
                     "San Luis Potosi, Mexico",
                     "Zacatecas, Mexico",
                     "San Luis Potosi, Mexico",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Durango, Mexico",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Coahuila, Mexico",
                     "Morelos, Mexico",
                     "Morelos, Mexico",
                     "Morelos, Mexico",
                     "Hidalgo, Mexico",
                     "State of Mexico, Mexico",
                     "Campeche, Mexico",
                     "Jalisco, Mexico",
                     "Jalisco, Mexico",
                     "Jalisco, Mexico",
                     "Nayarit, Mexico",
                     "Jalisco, Mexico",
                     "Jalisco, Mexico",
                     "Zacatecas, Mexico",
                     "Nuevo Leon, Mexico",
                     "Chihuahua, Mexico",
                     "Tamaulipas, Mexico",
                     "Durango, Mexico",
                     "Nuevo Leon, Mexico",
                     "Durango, Mexico",
                     "Mexico City, Mexico",
                     "Mexico City, Mexico",
                     "Chiapas, Mexico",
                     "Mexico City, Mexico",
                     "Chiapas, Mexico",
                     "Chiapas, Mexico",
                     "Chiapas, Mexico",
                     "Chiapas, Mexico",
                     "Hidalgo, Mexico",
                     "Chiapas, Mexico",
                     "Chiapas, Mexico",
                     "Chiapas, Mexico",
                     "Veracruz, Mexico",
                     "New York, USA",
                     "New York, USA",
                     "New York, USA",
                     "Veracruz, Mexico",
                     "Wisconsin, USA",
                     "Mississippi, USA",
                     "Georgia, USA",
                     "Alabama, USA",
                     "North Carolina, USA",
                     "North Carolina, USA",
                     "Florida, USA",
                     "Oklahoma, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "New Jersey, USA",
                     "Cayman Islands",
                     "Cayman Islands",
                     "Arizona, USA",
                     "New York, USA",
                     "Colorado, USA",
                     "Colorado, USA",
                     "Idaho, USA",
                     "Washington, USA",
                     "Washington, USA",
                     "Washington, USA",
                     "Washington, USA",
                     "Virginia, USA",
                     "Massachusetts, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "New Jersey, USA",
                     "Virginia, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "New Mexico, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Nevada, USA",
                     "Nevada, USA",
                     "Texas, USA",
                     "Oklahoma, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Nevada, USA",
                     "Delaware, USA",
                     "North Carolina, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "Wisconsin, USA",
                     "California, USA",
                     "California, USA",
                     "Texas, USA",
                     "Idaho, USA",
                     "California, USA",
                     "California, USA",
                     "Massachusetts, USA",
                     "Missouri, USA",
                     "Texas, USA",
                     "Quintana Roo, Mexico",
                     "North Carolina, USA",
                     "South Carolina, USA",
                     "South Carolina, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "New Mexico, USA",
                     "Massachusetts, USA",
                     "Utah, USA",
                     "Massachusetts, USA",
                     "Colorado, USA",
                     "Washington, USA",
                     "Washington, USA",
                     "Arizona, USA",
                     "San Luis Potosi, Mexico",
                     "Tabasco, Mexico",
                     "Jalisco, Mexico",
                     "Tamaulipas, Mexico",
                     "Tabasco, Mexico",
                     "Tabasco, Mexico",
                     "Tabasco, Mexico",
                     "Guerrero, Mexico",
                     "Veracruz, Mexico",
                     "Tabasco, Mexico",
                     "Tabasco, Mexico",
                     "Tabasco, Mexico",
                     "Tabasco, Mexico",
                     "Tabasco, Mexico",
                     "Tabasco, Mexico",
                     "Jeddah, Saudi Arabia",
                     "Guatemala, Guatemala",
                     "Alta Verapaz, Guatemala",
                     "Guatemala, Guatemala",
                     "Chimaltenango, Guatemala",
                     "Baja Verapaz, Guatemala",
                     "Guatemala",
                     "Guatemala",
                     "Guatemala",
                     "Guatemala",
                     "Guatemala",
                     "Guatemala",
                     "Guatemala",
                     "Nuevo Leon, Mexico",
                     "Oaxaca, Mexico",
                     "Baja California, Mexico",
                     "Veracruz, Mexico",
                     "Oaxaca, Mexico",
                     "Florida, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Florida, USA",
                     "West Sulawesi, Indonesia",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Arizona, USA",
                     "Arizona, USA",
                     "Minnesota, USA",
                     "West Java, Indonesia",
                     "Maryland, USA",
                     "Arizona, USA",
                     "Washington, USA",
                     "Michigan, USA",
                     "Michigan, USA",
                     "Coahuila, Mexico",
                     "Texas, USA",
                     "California, USA",
                     "Illinois, USA",
                     "Illinois, USA",
                     "Illinois, USA",
                     "Ohio, USA",
                     "Mexico City, Mexico",
                     "Washington, USA",
                     "Arizona, USA",
                     "Minnesota, USA",
                     "Sonora, Mexico",
                     "San Luis Potosi, Mexico",
                     "Minnesota, USA",
                     "Minnesota, USA",
                     "Minnesota, USA",
                     "Coahuila, Mexico",
                     "Puebla, Mexico",
                     "Puebla, Mexico",
                     "Minnesota, USA",
                     "Minnesota, USA",
                     "Arizona, USA",
                     "New York, USA",
                     "Nuevo Leon, Mexico",
                     "Nebraska, USA",
                     "Washington, USA",
                     "Washington, USA",
                     "Arizona, USA",
                     "Arizona, USA",
                     "Arizona, USA",
                     "Queretaro, Mexico",
                     "Nuevo Leon, Mexico",
                     "Queretaro, Mexico",
                     "Queretaro, Mexico",
                     "Tamaulipas, Mexico",
                     "Tamaulipas, Mexico",
                     "Tamaulipas, Mexico",
                     "Tamaulipas, Mexico",
                     "Minnesota, USA",
                     "Minnesota, USA",
                     "Minnesota, USA",
                     "Minnesota, USA",
                     "Minnesota, USA",
                     "Minnesota, USA",
                     "Minnesota, USA",
                     "Minnesota, USA",
                     "Minnesota, USA",
                     "Colorado, USA",
                     "Minnesota, USA",
                     "Nuevo Leon, Mexico",
                     "Mexico City, Mexico",
                     "Honduras",
                     "Honduras",
                     "Honduras",
                     "Honduras",
                     "Honduras",
                     "Honduras",
                     "Honduras",
                     "Honduras",
                     "Honduras",
                     "Honduras",
                     "Honduras",
                     "Honduras",
                     "Honduras",
                     "Guanajuato, Mexico",
                     "Chihuahua, Mexico",
                     "Nuevo Leon, Mexico",
                     "Tabasco, Mexico",
                     "Mexico City, Mexico",
                     "State of Mexico, Mexico",
                     "California, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Colorado, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Maryland, USA",
                     "Minnesota, USA",
                     "Minnesota, USA",
                     "Colorado, USA",
                     "Colorado, USA",
                     "Colorado, USA",
                     "Colorado, USA",
                     "Colorado, USA",
                     "Colorado, USA",
                     "Arizona, USA",
                     "Arizona, USA",
                     "Colorado, USA",
                     "Mexico City, Mexico",
                     "Jalisco, Mexico",
                     "Tamaulipas, Mexico",
                     "Washington, USA",
                     "Washington, USA",
                     "Washington, USA",
                     "California, USA",
                     "Chihuahua, Mexico",
                     "Minnesota, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "New York, USA",
                     "New York, USA",
                     "State of Mexico, Mexico",
                     "Arizona, USA",
                     "Wisconsin, USA",
                     "Washington, USA",
                     "Washington, USA",
                     "Washington, USA",
                     "Tamaulipas, Mexico",
                     "Tamaulipas, Mexico",
                     "California, USA",
                     "California, USA",
                     "Puebla, Mexico",
                     "Banten, Indonesia",
                     "Francisco Morazan, Honduras",
                     "El Paraiso, Honduras",
                     "La Paz, Honduras",
                     "Ocotepeque, Honduras",
                     "Ocotepeque, Honduras",
                     "Danli, Honduras",
                     "Atlantida, Honduras",
                     "San Jose, Costa Rica",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "Minnesota, USA",
                     "Sonora, Mexico",
                     "California, USA",
                     "California, USA",
                     "California, USA",
                     "Washington, USA",
                     "Washington, USA",
                     "Washington, USA",
                     "New Jersey, USA",
                     "Florida, USA",
                     "Tabasco, Mexico",
                     "Tabasco, Mexico",
                     "Tabasco, Mexico",
                     "Nuevo Leon, Mexico",
                     "Nuevo Leon, Mexico",
                     "Quintana Roo, Mexico",
                     "Tabasco, Mexico",
                     "California, USA",
                     "Tabasco, Mexico",
                     "Tabasco, Mexico",
                     "State of Mexico, Mexico",
                     "Texas, USA",
                     "New York, USA",
                     "New York, USA",
                     "New York, USA",
                     "Tabasco, Mexico",
                     "Kansas, USA",
                     "Alabama, USA",
                     "State of Mexico, Mexico",
                     "Minnesota, USA",
                     "Maryland, USA",
                     "Nayarit, Mexico",
                     "Puebla, Mexico",
                     "Maryland, USA",
                     "El Salvador",
                     "El Salvador",
                     "El Salvador",
                     "El Salvador",
                     "El Salvador",
                     "El Salvador",
                     "El Salvador",
                     "El Salvador",
                     "El Salvador",
                     "El Salvador",
                     "El Salvador",
                     "El Salvador",
                     "El Salvador",
                     "El Salvador",
                     "El Salvador",
                     "El Salvador",
                     "El Salvador",
                     "California, USA",
                     "New Jersey, USA",
                     "Minnesota, USA",
                     "Guatemala",
                     "Guatemala",
                     "Guatemala",
                     "Guatemala",
                     "Guatemala",
                     "Guatemala",
                     "Guatemala",
                     "Minnesota, USA",
                     "Arizona, USA",
                     "North Dakota, USA",
                     "North Dakota, USA",
                     "Idaho, USA",
                     "Idaho, USA",
                     "San Luis Potosi, Mexico",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Texas, USA",
                     "Coahuila, Mexico",
                     "North Carolina, USA",
                     "North Carolina, USA",
                     "North Carolina, USA",
                     "California, USA",
                     "Utah, USA",
                     "Tabasco, Mexico",
                     "Guatemala, Guatemala",
                     "Beirut, Lebanon")

# Run geocoding command (output in list format)
google_coord <- lapply(X = locations, ggmap::geocode, output = "all")

# Identify list names as original locations
names(google_coord) <- locations


# Convert geocoding output into dataframe (with custom command)
xb_geocoded <- lapply(google_coord, create_dt)
xb_geocoded_dt <- rbindlist(xb_geocoded, idcol = "SearchedAddress")
